import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MainThreeScene from "../three/MainThreeScene";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <MainThreeScene />
      </div>
    </div>
  );
};

export default Home;
