import type { NextPage } from "next";
import Head from "next/head";
import MainThreeScene from "../three/MainThreeScene";

import Image from "next/image";
import ScrambledText from "../components/ScrambledText";

const Hero = () => {
  return (
    <section className="hero">
      <header className="hero__header">
        <a href="">github</a>
        <a href="">контакты</a>
      </header>
      <div className="hero__foreground">
        <main className="hero__main">
          <h1 className="hero__headline">создаю ui даже во сне</h1>
          <span className="hero__scrambled">
            <ScrambledText
              shouldRepeat
              duration={90}
              classNames={{
                real: "scrambled-text",
                filler: "scrambled-text scrambled-text--type-filler",
              }}
              interval={3000}
              variability={0.3}
              sentences={["проекты", "vvv"]}
            />
          </span>
        </main>
      </div>
      <div className="hero__background">
        <MainThreeScene />
      </div>
    </section>
  );
};

const Projects = () => {
  return (
    <div className="project">
      <div className="project__description"></div>
      <div className="project__showcase">
        <Image
          src="/static/mock1-tp-comp-v2.png"
          alt="Tasty showcase"
          className="project__image"
          layout="fill"
          objectFit="contain"
        />
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Projects />
    </div>
  );
};

export default Home;
