import type { NextPage } from "next";
import Head from "next/head";
import MainThreeScene from "../three/MainThreeScene";

import Image from "next/image";
import ScrambledText from "../components/ScrambledText";

const Hero = () => {
  return (
    <section className="hero">
      <header className="hero__header">
        <a href="">github</a>
        <a href="">контакты</a>
      </header>
      <div className="hero__foreground">
        <main className="profile">
          <div className="profile__picture">
            <Image
              src={"/static/hero_pic.jpeg"}
              alt="profile picture"
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div className="profile__info">
            <div className="profile__bio">
              <h3 className="profile__name">евгений Родионов</h3>
              <span className="profile__title">фронтенд разработчик</span>
            </div>
            <h1 className="profile__headline">создаю ui даже во сне</h1>
            <span>
              <ScrambledText
                shouldRepeat
                duration={90}
                classNames={{
                  real: "scrambled-text",
                  filler: "scrambled-text scrambled-text--type-filler",
                }}
                interval={3000}
                variability={0.3}
                sentences={["проекты", "vvv"]}
              />
            </span>
          </div>
        </main>
      </div>
      <div className="hero__background">
        <MainThreeScene />
      </div>
    </section>
  );
};

const AnyProject = ({ name }: any) => {
  return (
    <div className="project">
      <div className="project__showcase">
        <div className="project__image">
          <Image
            src={`/static/projects/${name}`}
            alt="Tasty showcase"
            layout="fill"
            objectFit="contain"
          />
        </div>
      </div>
      <div className="project__description">hee</div>
    </div>
  );
};

const Projects = () => {
  return (
    <section className="projects">
      <AnyProject name={"ch-showcase.png"} />
      <AnyProject name={"di-showcase.png"} />
      <AnyProject name={"in-showcase.png"} />
    </section>
  );
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Projects />
    </div>
  );
};

export default Home;
