/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const ATTIC_MODEL_PATH = "/static/attic_model.glb";
const ENV_MAP_INTENSITY = 0.06;

type GLTFResult = GLTF & {
  nodes: {
    pCube815_lambert1_0: THREE.Mesh;
    pCube815_lambert1_0001: THREE.Mesh;
    pCube815_lambert1_0002: THREE.Mesh;
    pCube815_lambert1_0003: THREE.Mesh;
    pCube815_lambert1_0004: THREE.Mesh;
    pCube815_lambert4_0: THREE.Mesh;
    pCube815_lambert5_0: THREE.Mesh;
    pCube815_pasted__lambert3_0: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
    lambert4: THREE.MeshStandardMaterial;
    lambert5: THREE.MeshStandardMaterial;
    pasted__lambert3: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(ATTIC_MODEL_PATH) as GLTFResult;
  return (
    <group scale={[1, 1, 1]} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert1_0.geometry}
            // material={nodes.pCube815_lambert1_0.material}
          >
            <meshStandardMaterial
              metalness={0.1}
              roughness={0.5}
              envMapIntensity={ENV_MAP_INTENSITY}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert1_0001.geometry}
            // material={nodes.pCube815_lambert1_0001.material}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={1}
              envMapIntensity={ENV_MAP_INTENSITY}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert1_0002.geometry}
            // material={nodes.pCube815_lambert1_0002.material}
          >
            <meshStandardMaterial
              metalness={0.1}
              roughness={0.7}
              envMapIntensity={0.05}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert1_0003.geometry}
            // material={nodes.pCube815_lambert1_0003.material}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={1}
              envMapIntensity={0.045}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert1_0004.geometry}
            // material={nodes.pCube815_lambert1_0004.material}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={1}
              envMapIntensity={ENV_MAP_INTENSITY}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert4_0.geometry}
            // material={materials.lambert4}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={1}
              envMapIntensity={ENV_MAP_INTENSITY}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_lambert5_0.geometry}
            // material={materials.lambert5}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={1}
              envMapIntensity={ENV_MAP_INTENSITY}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube815_pasted__lambert3_0.geometry}
            // material={materials.pasted__lambert3}
          >
            <meshStandardMaterial
              metalness={0}
              roughness={0.7}
              envMapIntensity={0.05}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(ATTIC_MODEL_PATH);
